server:
  port: 8000

logging:
  level:
    org.springframework.web: DEBUG

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8314/eureka/
